export { Header } from './header' 
export { Footer } from './footer' 
export { TextInput } from './textinput'
export { SelectLanguage } from './SelectLanguage'
export { Loader } from './Loader'
export { Confidence } from './Confidence'
export { ExchangeLanguage } from './ExchangeLanguage'
export { TextCounter } from './TextCounter'